-- ─────────────────────────────────────────────────────────────────────────────
-- Migration: Create recommendation_feedback table — LPI Platform Phase 4
-- Owner  : Aryan (Backend Support & Schema)
-- Date   : 2026-06-21
-- ─────────────────────────────────────────────────────────────────────────────
--
-- WHY THIS TABLE EXISTS
-- ─────────────────────
-- Yashika's Phase 4 feedback loop needs somewhere to record when a user
-- accepts or dismisses a recommendation, so that choice can influence
-- future suggestions (e.g. don't keep re-surfacing something the user
-- already dismissed).
--
-- IMPORTANT — recommendations are NOT persisted anywhere.
-- lpi/recommendation_engine.py builds Recommendation objects on the fly on
-- every GET /api/v1/recommendations/{user_id} call, with a fresh
-- uuid4() id each time (see generate_recommendations() / sort + slice in
-- routers/recommendations.py). There is no `recommendations` table to
-- foreign-key against, and a recommendation_id is only ever meaningful in
-- the context of the API response the frontend rendered it from.
--
-- Because of that, this table SNAPSHOTS the parts of the recommendation
-- the user actually reacted to (action, smile_phase) instead of relying on
-- a join back to a row that won't exist by the time anyone reads this
-- table later. recommendation_id is still stored — it's useful for
-- deduplicating "did we already record feedback for this exact card" within
-- a single response — but it is NOT a foreign key.
--
-- FIELD DESIGN
-- ─────────────
-- recommendation_id : The ephemeral id from the Recommendation object the
--                      user was looking at. Not unique across time (every
--                      GET call mints new ids for what may be the "same"
--                      logical suggestion) — only unique within one
--                      response. No FK; see above.
--
-- action            : Snapshot of Recommendation.action at the moment of
--                      feedback. Keeps a feedback row self-describing even
--                      though the original recommendation is gone moments
--                      after the response was sent.
--
-- smile_phase        : Snapshot of Recommendation.smile_phase. Same 6-phase
--                      CHECK constraint as goals/activity_signals-adjacent
--                      tables, so a bad phase string can't sneak in here
--                      either (see models.SmilePhase / the hallucinated
--                      5-phase regression this project has already had to
--                      correct once).
--
-- status             : 'accepted' or 'dismissed'. The two reactions named
--                      explicitly in the Phase 4 plan ("when a user
--                      accepts or dismisses a recommendation").
--
-- No UNIQUE constraint on recommendation_id: a user could plausibly change
-- their mind (accept, then later dismiss), and that history is useful
-- signal for "future suggestions" rather than noise to dedupe away. If
-- Yashika's endpoint wants upsert-on-id semantics instead, that's an
-- application-layer decision, not a schema-layer one.
--
-- HOW TO APPLY THIS MIGRATION
-- ─────────────────────────────
-- Local dev:   supabase db push     (applies all unapplied migrations)
-- Verify:      supabase status      (check migration is listed)
-- Studio:      http://127.0.0.1:54323 → Table Editor → recommendation_feedback
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS recommendation_feedback (
    -- id: generated by Python (uuid.uuid4()), not by Postgres.
    -- TEXT type matches the goals/activity_signals convention in this project.
    id                 TEXT        PRIMARY KEY,

    -- user_id: whose feedback this is. Same DEFAULT as goals/activity_signals
    -- for consistency, though Phase 4 callers always have a real JWT subject
    -- by this point (Depends(get_current_user) on every router already).
    user_id            TEXT        NOT NULL DEFAULT 'default_user',

    -- recommendation_id: the ephemeral id of the card the user reacted to.
    -- See module comment above — intentionally NOT a foreign key.
    recommendation_id  TEXT        NOT NULL,

    -- action: snapshot of Recommendation.action at feedback time.
    action             TEXT        NOT NULL,

    -- smile_phase: snapshot of Recommendation.smile_phase at feedback time.
    -- Same 6 correct SMILE slugs as goals (data/smile-framework.json).
    smile_phase        TEXT        NOT NULL
                           CHECK (smile_phase IN (
                               'reality-emulation',
                               'concurrent-engineering',
                               'collective-intelligence',
                               'contextual-intelligence',
                               'continuous-intelligence',
                               'perpetual-wisdom'
                           )),

    -- status: the user's reaction. Only two values per the Phase 4 plan.
    status             TEXT        NOT NULL
                           CHECK (status IN ('accepted', 'dismissed')),

    -- created_at: when the feedback was recorded. Set by Python
    -- (datetime.now(UTC)) so it's consistent across all inserts, same as
    -- every other table in this project.
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Indexes ───────────────────────────────────────────────────────────────────
-- Pattern: one index per column the feedback-influenced-future-suggestions
-- logic is expected to filter or sort by (mirrors activity_signals).

-- Filter by user: "what has this user accepted/dismissed before".
CREATE INDEX IF NOT EXISTS idx_rf_user_id
    ON recommendation_feedback (user_id);

-- Look up feedback for a specific card shown in one response.
CREATE INDEX IF NOT EXISTS idx_rf_recommendation_id
    ON recommendation_feedback (recommendation_id);

-- Filter by reaction: e.g. "all of this user's dismissed actions" so the
-- engine can avoid re-surfacing them.
CREATE INDEX IF NOT EXISTS idx_rf_status
    ON recommendation_feedback (status);

-- Sort newest-first, same convention as activity_signals.idx_as_timestamp.
CREATE INDEX IF NOT EXISTS idx_rf_created_at
    ON recommendation_feedback (created_at DESC);


-- ── Row Level Security ───────────────────────────────────────────────────────
-- Same pattern as activity_signals (20260615000000_signals_rls_and_log_action.sql)
-- and goals (20260612000000_goals_rls.sql): the FastAPI backend uses the
-- service_role key and bypasses RLS — primary auth is still
-- Depends(get_current_user) in the router. RLS is the second layer, in case
-- the frontend ever queries Supabase directly.

ALTER TABLE recommendation_feedback ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users read own recommendation feedback"
    ON recommendation_feedback
    FOR SELECT
    USING (auth.uid()::text = user_id);

CREATE POLICY "Users insert own recommendation feedback"
    ON recommendation_feedback
    FOR INSERT
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users update own recommendation feedback"
    ON recommendation_feedback
    FOR UPDATE
    USING (auth.uid()::text = user_id)
    WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users delete own recommendation feedback"
    ON recommendation_feedback
    FOR DELETE
    USING (auth.uid()::text = user_id);


-- ── Audit log support ─────────────────────────────────────────────────────────
-- user_activity_logs.action has a CHECK constraint (20260607000000, extended
-- 20260615000000) that already bit the signals router once: a new action
-- value silently failed the CHECK and was only caught by a try/except in the
-- router. Adding the feedback actions here now avoids that exact failure
-- mode for Yashika's endpoint, whether or not she ends up calling
-- log_user_activity() for it.

ALTER TABLE user_activity_logs
    DROP CONSTRAINT IF EXISTS user_activity_logs_action_check;

ALTER TABLE user_activity_logs
    ADD CONSTRAINT user_activity_logs_action_check
    CHECK (action IN (
        'goal_created',
        'goal_updated',
        'goal_deleted',
        'signal_ingested',
        'recommendation_accepted',   -- added: Phase 4 feedback loop
        'recommendation_dismissed'   -- added: Phase 4 feedback loop
    ));
